# Data:
root_path: "/lithops-hpc/examples/mdr/data/tiny_100K_1f_1128p"
samples_file: "input/samples/chr0_synth000000.vcf"
patients_file: "input/labels.sample"
output_dir: "output-lhops"

# MDR parameters
CV_sets: 5
filter_imp: 0.9 # filter for imputation
prediction_power_tol: 2.2 # SNPij accumulative error tol
