# Data:
root_path: "$HOME/lithops-hpc-examples/mdr"
samples_file: "data/test1/samples/chr0_synth000000.vcf"
patients_file: "data/test1/samples/labels.sample"
output_dir: "data/test1/output"

# MDR parameters
CV_sets: 5
filter_imp: 0.9 # filter for imputation
prediction_power_tol: 2.3 # SNPij accumulative error tol
